version: '3.9'

services:
  container_250mhz_500mb:
    image: alpine
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500MB'
    command: sh -c "apk add --no-cache git nodejs npm bun deno && git clone https://github.com/your-nodejs-repo.git /app && cd /app && chmod +x run-benchmarks.sh && ./run-benchmarks.sh"

  container_500mhz_500mb:
    image: alpine
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500MB'
    command: sh -c "apk add --no-cache git nodejs npm bun deno && git clone https://github.com/your-nodejs-repo.git /app && cd /app && chmod +x run-benchmarks.sh && ./run-benchmarks.sh"

  container_1ghz_1gb:
    image: alpine
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1GB'
    command: sh -c "apk add --no-cache git nodejs npm bun deno && git clone https://github.com/your-nodejs-repo.git /app && cd /app && chmod +x run-benchmarks.sh && ./run-benchmarks.sh"

  container_2ghz_2gb:
    image: alpine
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2GB'
    command: sh -c "apk add --no-cache git nodejs npm bun deno && git clone https://github.com/your-nodejs-repo.git /app && cd /app && chmod +x run-benchmarks.sh && ./run-benchmarks.sh"

  container_2ghz_5gb:
    image: alpine
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '5GB'
    command: sh -c "apk add --no-cache git nodejs npm bun deno && git clone https://github.com/your-nodejs-repo.git /app && cd /app && chmod +x run-benchmarks.sh && ./run-benchmarks.sh"
